name: Docs

on:
  push:
    branches:
      - master

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.DOCS_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'velopack',
              repo: 'velopack.website',
              workflow_id: 'build.yml',
              ref: 'master'
            })